name: Latest blog post workflow
on:
  schedule: # Run workflow automatically 
    - cron: '0 * * * *' # Runs every hr
  workflow_dispatch: # Run workflow manually
jobs:
  update-readme-with-hashcode-blog:
    name: Update this repos README with the latest hashcode blogs posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-postworkflow@master
        with:
          feed_list: "https://medium.com/feed/@bhaveshharmalkar"
